emt:
  CAN_Control:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.7
      port: 10001
      extend: True
  CAN_Gears:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.8
      port: 10001
      extend: True
  CAN_Throttle:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.9
      port: 10001
      extend: True
  VehicleDecoder:
    ros__parameters:
      log_level: 0
      dictionary: emt_dictionary.yaml
  MCD60_Volante:
    ros__parameters:
      log_level: 0
      cobid: 3
      driver_type: epos
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 2000
      dictionary: epos_dictionary.yaml
      can: CAN_Control
      digital_outputs: 4
  MCD60_Freno:
    ros__parameters:
      log_level: 0
      cobid: 1
      driver_type: epos
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 2000
      dictionary: epos_dictionary.yaml
      can: CAN_Control
      digital_outputs: 4
      factor: 1
  CANADAC_Acelerador:
    ros__parameters:
      log_level: 10
      cobid: 5
      can: CAN_Throttle
  Arduino_Gears:
    ros__parameters:
      log_level: 10
      cobid: 8
      can: CAN_Gears
      dictionary: emt_gears_dictionary.yaml
  Brake:
    ros__parameters:
      log_level: 0
  Steering:
    ros__parameters:
      log_level: 0
  Throttle:
    ros__parameters:
      log_level: 0
  Gears:
    ros__parameters:
      log_level: 0
      dictionary: emt_gears_dictionary.yaml
  Longitudinal_Control:
    ros__parameters:
      log_level: 10
      speed_range: [ 0, 60 ]
      throttle:
        kp: 3
        ti: 2
        td: 0
      brake:
        kp: 0.5
        ti: 4
        td: 0