gdels:
  CAN_Control:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.7
      port: 10001
      extend: False
  CANADAC_Acelerador:
    ros__parameters:
      log_level: 10
      cobid: 5
      can: CAN_Control
  GDELSDecoder:
    ros__parameters:
      log_level: 0
      dictionary: maqueta_dictionary.yaml
  EPOS4_Volante:
    ros__parameters:
      log_level: 0
      cobid: 3
      driver_type: epos
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 5000
      dictionary: epos_dictionary.yaml
      can: CAN_Control
      digital_outputs: 4
      factor: 1
  MCD60_Freno:
    ros__parameters:
      log_level: 0
      cobid: 1
      driver_type: epos
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 1000
      dictionary: epos_dictionary.yaml
      can: CAN_Control
      digital_outputs: 4
      factor: 1
  Brake:
    ros__parameters:
      log_level: 0
  Steering:
    ros__parameters:
      log_level: 0
  Throttle:
    ros__parameters:
      log_level: 0
  Longitudinal_Control:
    ros__parameters:
      log_level: 0
      throttle:
        kp: 3.
        ti: 0.
        td: 0.
        windup: 0.3
      brake:
        #follow-me
        kp: 6.
        ti: 4.
        td: 0.
        #normal
#        kp: 2.
#        ti: 3.
#        td: 0.
        windup: 0.65
      static_brake: 0.75
  Lateral_Control:
    ros__parameters:
      log_level: 0
      steering:
        # Follow
        kp: 5.
        ti: 0.
        td: 0.
        # A6
        #kp: 10
        #ti: 8
        #td: 0.03
        # Pista
        #kp: 1.0
        #ti: 1.0
        #td: 0.0
        windup: 0.0
  Decision:
    ros__parameters:
      log_level: 0
      wp:
        mode: 'wheels'
        ttl: 1
      tele:
        mode: 'wheels'
        ttl: 0