imiev:
  CAN_6:
    ros__parameters:
      log_level: 0
      local: True # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.6
      port: 10001
      extend: False
  CAN_7:
    ros__parameters:
      log_level: 0
      local: True # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.7
      port: 10001
      extend: False
  EPOS4_Volante:
    ros__parameters:
      log_level: 0
      cobid: 2
      driver_type: epos4
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 2000
      dictionary: epos4_dictionary.yaml
      can: CAN_7
      digital_outputs: 2
  MCD60_Freno:
    ros__parameters:
      log_level: 0
      cobid: 1
      driver_type: epos
      mode: PPM #PPM: Profile position mode, TODO:Por ahora solo funciona en profile position mode
      auto_fault_reset: True
      speed: 2000
      dictionary: epos_dictionary.yaml
      can: CAN_7
      digital_outputs: 4
  CANADAC:
    ros__parameters:
      log_level: 10
      cobid: 5
      can: CAN_7
  ImievDecoder:
    ros__parameters:
      log_level: 0
      dictionary: imiev_dictionary.yaml
#  Arduino_Gears:
#    ros__parameters:
#      log_level: 10
#      cobid: 8
#      can: CAN_7
#      dictionary: emt_gears_dictionary.yaml
#      dict_BigEndian: True # True si es big endian False si está en little endian
  Brake:
    ros__parameters:
      log_level: 0
  Steering:
    ros__parameters:
      log_level: 0
  Throttle:
    ros__parameters:
      log_level: 0
  Longitudinal_Control:
    ros__parameters:
      log_level: 10
      speed_range: [0, 120]
      throttle:
        kp: 3
        ti: 2
        td: 0
      brake:
        kp: 0.5
        ti: 4
        td: 0