imiev:
  CAN_6:
    ros__parameters:
      log_level: 0
      local: True # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.6
      port: 10001
      extend: False
  CAN_7:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.7
      port: 10001
      extend: False
  EPOS4_Volante:
    ros__parameters:
      log_level: 0
      cobid: 2
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 2000
      dictionary: epos4_dictionary.yaml
      can: CAN_7
  MCD60_Freno:
    ros__parameters:
      log_level: 10
      cobid: 1
      mode: PPM #PPM: Profile position mode, TODO:Por ahora solo funciona en profile position mode
      auto_fault_reset: True
      speed: 2000
      dictionary: epos_dictionary.yaml
      can: CAN_7
  CANADAC:
    ros__parameters:
      log_level: 10
      cobid: 5
      can: CAN_7
  ImievDecoder:
    ros__parameters:
      log_level: 0
      dictionary: imiev_dictionary.yaml