imiev:
  CAN_6:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.6
      port: 10001
      extend: False
  CAN_7:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.8
      port: 10001
      extend: False
  CANADAC_Acelerador:
    ros__parameters:
      log_level: 10
      cobid: 5
      can: CAN_7
  ImievDecoder:
    ros__parameters:
      log_level: 0
      dictionary: imiev_dictionary.yaml
  EPOS4_Volante:
    ros__parameters:
      log_level: 0
      cobid: 2
      driver_type: epos4
      mode: CST #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 2000
      dictionary: epos4_dictionary.yaml
      can: CAN_7
      digital_outputs: 2
  FAULHABER_Freno:
    ros__parameters:
      log_level: 0
      cobid: 1
      can: CAN_7
  #  Arduino_Gears:
  #    ros__parameters:
  #      log_level: 10
  #      cobid: 8
  #      can: CAN_7
  #      dictionary: emt_gears_dictionary.yaml
  #      dict_BigEndian: True # True si es big endian False si está en little endian
  Brake:
    ros__parameters:
      log_level: 0
  Steering:
    ros__parameters:
      log_level: 0
  Throttle:
    ros__parameters:
      log_level: 0
  Longitudinal_Control:
    ros__parameters:
      log_level: 0
      throttle:
        kp: 3
        ti: 2
        td: 0
      brake:
        kp: 0.5
        ti: 4
        td: 0
  Lateral_Control:
    ros__parameters:
      log_level: 0
      steering:
        # A6
        #        kp: 10
        #        ti: 8
        #        td: 0.03
        # Pista
        kp: 0.3
        ti: 0.2
        td: 0.1
  Decision:
    ros__parameters:
      log_level: 0
      wp:
        mode: 'wheels'
        ttl: 1
      tele:
        mode: 'wheels'
        ttl: 1