imiev:
  CAN_6:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.6
      port: 10001
      extend: False
  CAN_7:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 192.168.0.8
      port: 10001
      extend: False
  EPOS4_Volante:
    ros__parameters:
      log_level: 10
      cobid: 3
      mode: CST #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      dictionary: epos.yaml
  MCD60_Freno:
    ros__parameters:
      log_level: 10
      cobid: 2
      mode: PPM #PPM: Profile position mode, TODO:Por ahora solo funciona en profile position mode
      fault_reset: True
      dictionary: epos.yaml
  CANADAC:
    ros__parameters:
      log_level: 10
      cobid: 5
      can: CAN_7
  ImievDecoder:
    ros__parameters:
      log_level: 0
      dictionary: imiev_dictionary.yaml