lagarto:
  CAN_Vehiculo:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: udp
      ip: 192.168.0.20
      port: 20000
      extend: True
  CAN_Control:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: udp
      ip: 192.168.0.10
      port: 20000
      extend: True
  EPOS_Volante:
    ros__parameters:
      log_level: 0
      cobid: 3
      driver_type: epos
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 5000
      dictionary: epos_dictionary.yaml
      can: CAN_Control
      digital_outputs: 4
  MCD60_Freno:
    ros__parameters:
      log_level: 0
      cobid: 1
      driver_type: epos
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 5000
      dictionary: epos_dictionary.yaml
      can: CAN_Control
      digital_outputs: 4
  CANADAC_Acelerador:
    ros__parameters:
      log_level: 0
      cobid: 5
      can: CAN_Control
  Arduino_Gears:
    ros__parameters:
      log_level: 0
      cobid: 6
      can: CAN_Control
      dictionary: lagarto_gears_dictionary.yaml
  Arduino_DumpBox:
    ros__parameters:
      log_level: 0
      cobid: 7
      can: CAN_Control
      dictionary: lagarto_dump_box_dictionary.yaml
  LagartoDecoder:
    ros__parameters:
      log_level: 0
      dictionary: lagarto_dictionary.yaml
  Brake:
    ros__parameters:
      log_level: 0
  Steering:
    ros__parameters:
      log_level: 0
  Throttle:
    ros__parameters:
      log_level: 0
  Gears:
    ros__parameters:
      log_level: 0
      dictionary: lagarto_gears_dictionary.yaml
  DumpBox:
    ros__parameters:
      log_level: 0
  Longitudinal_Control:
    ros__parameters:
      log_level: 0
      throttle:
        kp: 3
        ti: 2
        td: 0
      brake:
        kp: 0.5
        ti: 4
        td: 0
  Lateral_Control:
    ros__parameters:
      log_level: 0
      # steering_range: [ -630, 630 ]
      steering:
        kp: 10
        ti: 8
        td: 0.03
  Gears_Control:
    ros__parameters:
      log_level: 0
  Decision:
    ros__parameters:
      log_level: 0
      lidar_priority: 2 # Prioridad en la que está el lidar
      subscribers:
        0:
          topic: /Joy
          ttl: 1 #secs

