gdels:
  CANADAC_Acelerador:
    ros__parameters:
      log_level: 10
      cobid: 5
      can: CAN_Control
  LagartoDecoder:
    ros__parameters:
      log_level: 0
      dictionary: lagarto_dictionary.yaml
  MCD60_Volante:
    ros__parameters:
      log_level: 0
      cobid: 3
      driver_type: epos
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 5000
      dictionary: epos_dictionary.yaml
      can: CAN_Control
      digital_outputs: 4
      factor: 1
  MCD60_Freno:
    ros__parameters:
      log_level: 0
      cobid: 1
      driver_type: epos
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 5000
      dictionary: epos_dictionary.yaml
      can: CAN_Control
      digital_outputs: 4
      factor: 1
  Brake:
    ros__parameters:
      log_level: 0
  Steering:
    ros__parameters:
      log_level: 0
  Throttle:
    ros__parameters:
      log_level: 0
  Lateral_Control:
    ros__parameters:
      log_level: 0
      # steering_range: [ -630, 630 ]
      steering:
        kp: 10
        ti: 8
        td: 0.03
  Decision:
    ros__parameters:
      log_level: 0
      wp:
        mode: 'wheels'
        ttl: 1
      tele:
        mode: 'wheels'
        ttl: 0
  Longitudinal_Control:
    ros__parameters:
      log_level: 0
      throttle:
        kp: 3.
        ti: 0.
        td: 0.
        windup: 0.3
      brake:
        #follow-me
        kp: 6.
        ti: 4.
        td: 0.
        #normal
        #        kp: 2.
        #        ti: 3.
        #        td: 0.
        windup: 0.65
      static_brake: 0.75