/**:
  CAN_MUTT:
    ros__parameters:
      log_level: 0
      local: False # Poner a true si no esta conectado al vehiculo para poder ver laa conexion de los topics
      connection_mode: tcp
      ip: 10.4.0.10
      port: 10001
      extend: False
#  VehicleDecoder:
#    ros__parameters:
#      log_level: 0
#      dictionary: ascod_dictionary.yaml
  CANADAC_MUTT:
    ros__parameters:
      log_level: 0
      cobid: 0x100
      can: CAN_MUTT
      dictionary: CANAMUTT_dictionary.yaml
  Control_MUTT:
    ros__parameters:
      log_level: 10
      throttle:
        kp: 2.0
        ki: 0.5
        kd: 0.0
        i_windup: 1.0
        ff_0kmh: 0.0
        ff_1kmh: 0.1
        ff_2kmh: 0.14
        ff_3kmh: 0.18
        ff_4kmh: 0.2
  Decision:
    ros__parameters:
      log_level: 0
      wp:
        mode: 'wheels'
        ttl: 1
      tele:
        mode: 'steering_wheel'
        ttl: 0
      follow_me:
        mode: 'wheels'
        ttl: 0
      radio_control:
        mode: 'steering_wheel'
        ttl: 0
      nav2:
        mode: 'wheels'
        ttl: 0
