ascod:
  can_control:
    ros__parameters:
      log_level: 0
      can: can1
  VehicleDecoder:
    ros__parameters:
      log_level: 0
      dictionary: ascod_dictionary.yaml
  CANADAC_Acelerador:
    ros__parameters:
      log_level: 10
      cobid: 5
      can: can_control
  MCD60_Volante:
    ros__parameters:
      log_level: 0
      cobid: 3
      driver_type: epos
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 2000
      dictionary: epos_dictionary.yaml
      can: can_control
      digital_outputs: 4
  EPOS4_Freno:
    ros__parameters:
      log_level: 0
      cobid: 1
      driver_type: epos4
      mode: PPM #CST: Cyclic Synchronous Torque Mode, PPM: Profile position mode TODO: CST para volante imiev, para EC90 usar PPM
      auto_fault_reset: True
      speed: 5000
      dictionary: epos_dictionary.yaml
      can: can_control
      digital_outputs: 2
      factor: 1

  Arduino_Gears:
    ros__parameters:
      log_level: 0
      cobid: 8
      can: can_control
      dictionary: ascod_gears_dictionary.yaml
  Brake:
    ros__parameters:
      log_level: 0
  Steering:
    ros__parameters:
      log_level: 0
  Throttle:
    ros__parameters:
      log_level: 0
  Gears:
    ros__parameters:
      log_level: 0
      dictionary: ascod_gears_dictionary.yaml
  Longitudinal_Control:
    ros__parameters:
      log_level: 0
      throttle:
        kp: 1.5 # 3.5
        ti: 0.7 # 3
        td: 0. # 0
        windup: 0.3
      brake:
        kp: 3.
        ti: 0.5
        td: 0
        windup: 0.65
      static_brake: 0.9
  Lateral_Control:
    ros__parameters:
      log_level: 0
      # steering_range: [ -630, 630 ]
      steering:
        kp: 10
        ti: 8
        td: 0.03
  Gears_Control:
    ros__parameters:
      log_level: 0
  Decision:
    ros__parameters:
      log_level: 0
      wp:
        mode: 'steering_wheel'
        ttl: 1
      tele:
        mode: 'steering_wheel'
        ttl: 1
  PathPlanning:
    ros__parameters:
      log_level: 0
