import os
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    parameters_file_path_ascod = '{}/../conf/ascod.yaml'.format(
        os.path.abspath(os.path.dirname(os.path.realpath(__file__))))
    return LaunchDescription([
        Node(
            package='INSIA_control',
            executable='can',
            name='CAN_6_Vehicle',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
        Node(
            package='INSIA_control',
            executable='can',
            name='CAN_7_EPOS',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
        Node(
            package='INSIA_control',
            executable='telemetry_ascod',
            name='VehicleDecoder',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
        Node(
            package='INSIA_control',
            executable='maxon',
            name='EPOS4_Freno',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
        Node(
            package='INSIA_control',
            executable='ascod_placa_azul',
            name='CANADAC_Acelerador',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
        Node(
            package='INSIA_control',
            executable='brake_ascod',
            name='Brake',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
        Node(
            package='INSIA_control',
            executable='throttle_ascod',
            name='Throttle',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
        Node(
            package='INSIA_control',
            executable='longitudinal_control_simple',
            name='Longitudinal_Control',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
        Node(
            package='INSIA_control',
            executable='decision_simulador',
            name='Decision',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
        Node(
            package='INSIA_control',
            executable='pathplanning_basic',
            name='PathPlanning',
            parameters=[parameters_file_path_ascod],
            output='screen',
            emulate_tty=True
        ),
    ])